# Generated by Django 2.2.4 on 2020-05-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0004_auto_20200502_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
