# Generated by Django 2.2.4 on 2020-05-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0006_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
